name: "KiCad CI/CD for INTERFACE"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    paths:
      - 'Electrical/Design/INTERFACE/INTERFACE/*.kicad_sch'
      - 'Electrical/Design/INTERFACE/INTERFACE/*.kicad_pcb'
      - 'Electrical/Design/INTERFACE/INTERFACE/*.kibot.yaml'
      - 'Electrical/Design/INTERFACE/INTERFACE/Makefile'
      - '.github/workflows/INTERFACE.yml'
      - '.github/workflows/convert_bottom_position.py'
  pull_request:
    paths:
      - 'Electrical/Design/INTERFACE/INTERFACE/*.kicad_sch'
      - 'Electrical/Design/INTERFACE/INTERFACE/*.kicad_pcb'
      - 'Electrical/Design/INTERFACE/INTERFACE/*.kibot.yaml'
      - 'Electrical/Design/INTERFACE/INTERFACE/Makefile'
      - '.github/workflows/INTERFACE.yml'
      - '.github/workflows/convert_bottom_position.py'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  FabPCB:
    name: PCB fabrication files
    runs-on: ubuntu-latest
    container: "setsoft/kicad_auto:dev_k6"

    steps:
    - uses: actions/checkout@v2

    - name: Run PCB stuff
      run: |
        make -C Electrical/Design/INTERFACE/INTERFACE

    - name: Retrieve results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: FabPCB_Output
        path: |
          Electrical/Design/INTERFACE/INTERFACE/mfg-bot/
          Electrical/Design/INTERFACE/INTERFACE/kibot_error.log
        if-no-files-found: warn

    - name: Print errors
      if: ${{ always() }}
      run: |
        cat Electrical/Design/INTERFACE/INTERFACE/mfg-bot/INTERFACE-drc.txt
        cat Electrical/Design/INTERFACE/INTERFACE/kibot_error.log

    - name: Zipping artifacts      
      uses: vimtor/action-zip@v1
      with:
        files: Electrical/Design/INTERFACE/INTERFACE/mfg-bot/JLCPCB
        dest: "Electrical/Design/INTERFACE/INTERFACE/mfg-bot/mfg/INTERFACE-gerber.zip"

